name: ReVanced Test Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Setup Java JDK
        uses: actions/setup-java@v3.5.1
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Download APKs from APKMirror
        run: ./download_apkmirror.sh

      - name: Test Build APKs
        run: |
          ./build_revanced.sh
          for filename in build/revanced-root.apk build/revanced-nonroot.apk build/revanced-music-root.apk build/revanced-music-nonroot.apk; do
            if [ -e "$filename" ]; then
              printf '"%s" exists\n' "$filename"
            else
              echo "APK build failed"
              exit 1
            fi
          done
          rm -rf build
